PlateFormeBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: PlateFormeBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        contenu:
            type: text
        parent:
            type: integer
            nullable: true
        enfant:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
