plate_forme:
    resource: "@PlateFormeBundle/Resources/config/routing.yml"
    prefix:   /

haras:
    resource: "@HarasBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@HarasBundle/Resources/config/routing/all.xml"