plate_forme:
    resource: "@PlateFormeBundle/Resources/config/routing.yml"
    prefix:   /plateforme

haras:
    resource: "@HarasBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@UserBundle/Resources/config/routing/all.xml"

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"