plate_forme_homepage:
    path:     /
    defaults: { _controller: PlateFormeBundle:Default:index }

plate_forme_agenda:
    resource: "@PlateFormeBundle/Resources/config/routing/agenda.yml"
    prefix:   /agenda
