plate_forme_homepage:
    path:     /
    defaults: { _controller: PlateFormeBundle:Default:index }

#Route Calendar
adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"
    prefix:   /

fullcalendar_loader:
    path: /pfc-load-calendar-events
    defaults: { _controller: ADesignsCalendarBundle:Calendar:loadCalendar }
    options:
        expose: true

plate_forme_agenda:
    resource: "@PlateFormeBundle/Resources/config/routing/agenda.yml"
    prefix:   /agenda

#FOS JS Routing ==> permet de convertir route php en js
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix:   /